import type { User, GPT, ChatSession, ChatMessage } from "@/types"

export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "john.doe@example.com",
    full_name: "John Doe",
    role: "user",
    team_id: "team-1",
    team_name: "Strategic Support Team",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: "admin-1",
    email: "sarah.johnson@example.com",
    full_name: "Sarah Johnson",
    role: "admin",
    team_id: "team-1",
    team_name: "Strategic Support Team",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: "superadmin-1",
    email: "jane.smith@example.com",
    full_name: "Jane Smith",
    role: "super_admin",
    team_id: "org",
    team_name: "Organization-wide",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: "user-2",
    email: "alice.williams@example.com",
    full_name: "Alice Williams",
    role: "user",
    team_id: "team-2",
    team_name: "Finance Team",
    avatar: "/placeholder-user.jpg",
  },
  {
    id: "admin-2",
    email: "michael.chen@example.com",
    full_name: "Michael Chen",
    role: "admin",
    team_id: "team-2",
    team_name: "Finance Team",
    avatar: "/placeholder-user.jpg",
  },
]

export const mockGPTs: GPT[] = [
  {
    id: "gpt-1",
    name: "LegalGPT",
    description: "Specialized assistant for legal document review and compliance.",
    team_name: "Strategic Support Team",
    last_used: "Jul 15",
    usage_count: 128,
    status: "active",
    created_by: "Sarah Johnson",
    web_access: true,
    approval_status: "approved",
    created_at: "2024-01-10T10:00:00Z",
    updated_at: "2024-01-15T14:30:00Z",
    active_users: 23,
    model: "GPT-4",
    monthly_cost: 45.67,
    compliance_score: 95,
    risk_level: "low",
    access_level: "team",
  },
  {
    id: "gpt-2",
    name: "FinanceBot",
    description: "Financial analysis and reporting assistant for Q2 forecasts.",
    team_name: "Finance Team",
    last_used: "Jul 14",
    usage_count: 89,
    status: "active",
    created_by: "Michael Chen",
    web_access: false,
    approval_status: "approved",
    created_at: "2024-01-08T14:20:00Z",
    updated_at: "2024-01-14T11:45:00Z",
    active_users: 15,
    model: "GPT-4",
    monthly_cost: 28.93,
    compliance_score: 88,
    risk_level: "low",
    access_level: "team",
  },
  {
    id: "gpt-3",
    name: "GlobalReportWriter",
    description: "Organization-wide report generation and analysis tool.",
    team_name: "Organization-wide",
    last_used: "Jul 15",
    usage_count: 456,
    status: "active",
    created_by: "Jane Smith",
    web_access: true,
    approval_status: "approved",
    created_at: "2024-01-05T09:15:00Z",
    updated_at: "2024-01-15T16:20:00Z",
    active_users: 67,
    model: "GPT-4",
    monthly_cost: 123.45,
    compliance_score: 92,
    risk_level: "medium",
    access_level: "organization",
  },
  {
    id: "gpt-4",
    name: "HR Assistant",
    description: "Human resources support and policy guidance.",
    team_name: "Learning and Development",
    last_used: "Jul 12",
    usage_count: 45,
    status: "pending",
    created_by: "HR Team",
    web_access: false,
    approval_status: "pending",
    created_at: "2024-01-12T09:15:00Z",
    updated_at: "2024-01-12T16:20:00Z",
    active_users: 8,
    model: "GPT-3.5",
    monthly_cost: 4.56,
    compliance_score: 78,
    risk_level: "medium",
    access_level: "team",
  },
  {
    id: "gpt-5",
    name: "DataAnalyzer",
    description: "Advanced data analysis and visualization tool.",
    team_name: "Revenue Growth Unit",
    last_used: "Jul 10",
    usage_count: 156,
    status: "suspended",
    created_by: "Data Team",
    web_access: true,
    approval_status: "rejected",
    created_at: "2024-01-01T08:00:00Z",
    updated_at: "2024-01-10T12:30:00Z",
    active_users: 12,
    model: "GPT-4",
    monthly_cost: 15.67,
    compliance_score: 65,
    risk_level: "high",
    access_level: "team",
  },
]

export const mockChatSessions: ChatSession[] = [
  {
    id: "chat-session-1",
    user_id: "user-1",
    gpt_id: "gpt-1",
    gpt_name: "LegalGPT",
    title: "Draft NDA for vendor partnership",
    created_at: "2024-01-15T14:30:00Z",
    updated_at: "2024-01-15T15:45:00Z",
    message_count: 12,
    status: "completed",
  },
  {
    id: "chat-session-2",
    user_id: "user-1",
    gpt_id: "gpt-3",
    gpt_name: "GlobalReportWriter",
    title: "Q2 Strategic analysis report",
    created_at: "2024-01-14T11:15:00Z",
    updated_at: "2024-01-14T16:20:00Z",
    message_count: 8,
    status: "active",
  },
  {
    id: "chat-session-3",
    user_id: "admin-1",
    gpt_id: "gpt-1",
    gpt_name: "LegalGPT",
    title: "Review contract terms and conditions",
    created_at: "2024-01-13T16:45:00Z",
    updated_at: "2024-01-13T17:30:00Z",
    message_count: 15,
    status: "completed",
  },
  {
    id: "chat-session-4",
    user_id: "user-2",
    gpt_id: "gpt-2",
    gpt_name: "FinanceBot",
    title: "Employee onboarding checklist",
    created_at: "2024-01-12T09:20:00Z",
    updated_at: "2024-01-12T10:45:00Z",
    message_count: 6,
    status: "archived",
  },
  {
    id: "chat-session-5",
    user_id: "superadmin-1",
    gpt_id: "gpt-3",
    gpt_name: "GlobalReportWriter",
    title: "Policy compliance review",
    created_at: "2024-01-11T13:10:00Z",
    updated_at: "2024-01-11T14:25:00Z",
    message_count: 9,
    status: "completed",
  },
  {
    id: "chat-session-6",
    user_id: "user-1",
    gpt_id: "gpt-1",
    gpt_name: "LegalGPT",
    title: "New vendor agreement draft",
    created_at: "2024-01-16T09:00:00Z",
    updated_at: "2024-01-16T09:45:00Z",
    message_count: 7,
    status: "active",
  },
]

export const mockChatMessages: ChatMessage[] = [
  {
    id: "msg-1-1",
    session_id: "chat-session-1",
    sender: "user",
    content: "I need a draft NDA for a new vendor partnership. Can you help?",
    created_at: "2024-01-15T14:30:10Z",
  },
  {
    id: "msg-1-2",
    session_id: "chat-session-1",
    sender: "gpt",
    content:
      "Please provide the names of the parties involved and any specific clauses you'd like to include or exclude.",
    created_at: "2024-01-15T14:30:45Z",
  },
  {
    id: "msg-1-3",
    session_id: "chat-session-1",
    sender: "user",
    content: "Party A: Acme Corp, Party B: Global Solutions. Standard confidentiality, non-compete for 2 years.",
    created_at: "2024-01-15T14:31:30Z",
  },
  {
    id: "msg-2-1",
    session_id: "chat-session-2",
    sender: "user",
    content: "Generate a summary of the Q2 performance based on the attached data.",
    created_at: "2024-01-14T11:15:20Z",
  },
  {
    id: "msg-2-2",
    session_id: "chat-session-2",
    sender: "gpt",
    content: "Please upload the data file. Once uploaded, I can begin the analysis.",
    created_at: "2024-01-14T11:15:55Z",
  },
  {
    id: "msg-3-1",
    session_id: "chat-session-3",
    sender: "user",
    content: "Can you review this contract for potential risks?",
    created_at: "2024-01-13T16:45:10Z",
  },
  {
    id: "msg-5-1",
    session_id: "chat-session-5",
    sender: "user",
    content: "What are the key compliance requirements for data handling in Europe?",
    created_at: "2024-01-11T13:10:05Z",
  },
  {
    id: "msg-5-2",
    session_id: "chat-session-5",
    sender: "gpt",
    content:
      "The primary regulation is GDPR. It covers data protection and privacy for all individuals within the EU and EEA. Key principles include lawfulness, fairness, transparency, purpose limitation, data minimization, accuracy, storage limitation, integrity, and confidentiality.",
    created_at: "2024-01-11T13:11:00Z",
  },
]
