import type { GPT } from "@/types"

// In-memory mock data for GPTs
export const mockGptsData: GPT[] = [
  {
    id: "gpt-1",
    name: "LegalGPT",
    description: "Specialized assistant for legal document review and compliance.",
    team_name: "Strategic Support Team",
    last_used: "Jul 15",
    usage_count: 128,
    status: "active",
    created_by: "Sarah Johnson",
    web_access: true,
    approval_status: "approved",
    created_at: "2024-01-10T10:00:00Z",
    updated_at: "2024-01-15T14:30:00Z",
    active_users: 23,
    model: "GPT-4",
    monthly_cost: 45.67,
    compliance_score: 95,
    risk_level: "low",
    access_level: "team",
  },
  {
    id: "gpt-2",
    name: "FinanceBot",
    description: "Financial analysis and reporting assistant for Q2 forecasts.",
    team_name: "Finance Team",
    last_used: "Jul 14",
    usage_count: 89,
    status: "active",
    created_by: "Michael Chen",
    web_access: false,
    approval_status: "approved",
    created_at: "2024-01-08T14:20:00Z",
    updated_at: "2024-01-14T11:45:00Z",
    active_users: 15,
    model: "GPT-4",
    monthly_cost: 28.93,
    compliance_score: 88,
    risk_level: "low",
    access_level: "team",
  },
  {
    id: "gpt-3",
    name: "GlobalReportWriter",
    description: "Organization-wide report generation and analysis tool.",
    team_name: "Organization-wide",
    last_used: "Jul 15",
    usage_count: 456,
    status: "active",
    created_by: "Jane Smith",
    web_access: true,
    approval_status: "approved",
    created_at: "2024-01-05T09:15:00Z",
    updated_at: "2024-01-15T16:20:00Z",
    active_users: 67,
    model: "GPT-4",
    monthly_cost: 123.45,
    compliance_score: 92,
    risk_level: "medium",
    access_level: "organization",
  },
  {
    id: "gpt-4",
    name: "HR Assistant",
    description: "Human resources support and policy guidance.",
    team_name: "Learning and Development",
    last_used: "Jul 12",
    usage_count: 45,
    status: "pending",
    created_by: "HR Team",
    web_access: false,
    approval_status: "pending",
    created_at: "2024-01-12T09:15:00Z",
    updated_at: "2024-01-12T16:20:00Z",
    active_users: 8,
    model: "GPT-3.5",
    monthly_cost: 4.56,
    compliance_score: 78,
    risk_level: "medium",
    access_level: "team",
  },
  {
    id: "gpt-5",
    name: "DataAnalyzer",
    description: "Advanced data analysis and visualization tool.",
    team_name: "Revenue Growth Unit",
    last_used: "Jul 10",
    usage_count: 156,
    status: "suspended",
    created_by: "Data Team",
    web_access: true,
    approval_status: "rejected",
    created_at: "2024-01-01T08:00:00Z",
    updated_at: "2024-01-10T12:30:00Z",
    active_users: 12,
    model: "GPT-4",
    monthly_cost: 15.67,
    compliance_score: 65,
    risk_level: "high",
    access_level: "team",
  },
]
